config/routes.rb
Rails.application.routes.draw do
 
  get 'pages/home'

  get 'pages/contact'

  resources :charges
  resources :payments
  resources :memberships
  get 'pages/index'
  # post 'profiles/index'
  # patch 'profiles/index'
  get 'home/index'
  root "home#index"
  resources :profiles
  resources :posts
  resources :drinks
  devise_for :users
  get 'profiles/edit'
  get 'profiles/show' 
  get 'profiles/new'
  # delete 'profiles/id', to: 'profiles#destroy'
  get 'posts/new'
  # get 'posts/show'
  post 'pages/contact', to: 'pages#contact_email'
  post 'profiles', to: 'profiles#profile'
  post 'posts', to: 'posts#post' 
  get '/tables', to: 'tables#all_tables' 
  get '/tables/table/:table_name', to: 'tables#table', as: 'table'


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  

end

app/models/profile.rb
class Profile < ApplicationRecord
  include ImageUploader::Attachment.new(:image) # adds an "image" virtual attribute
  belongs_to :user
  has_many :reviews
  has_many :followers
  has_many :posts
  has_many :drinks, through: :posts
  validates :user, presence: true

  def image_display(args)
    if image_data
      image_url(args)
    else
      "http://via.placeholder.com/80x80"
     end
  end
end

   

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :check_profile_presence, only: [:new, :create]
  before_action :set_profile, only: [:show, :edit, :update, :new, :create]
  # before_action :auth_actions, only: [:update, :edit]
  before_action :authenticate_user!, except: [:index, :show]

  
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
    authorize @profiles 
  end

def user
  user = current_user
end 

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      puts "PROFILE_PARAMS"
      puts profile_params
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 



  private

  def check_profile_presence 
    # @profile = Profile.current_user
    # @profile = Profile.find(params[:id])
    #  if Profile.params[:id]!= nil redirect_to profile_path
    if !current_user.profile.nil? 
      redirect_to root_url, notice: 'Profile already exists for this account.'
    
    # end
    # else 
    #   new_profile_path
    # if @profile.user != current_user
      # redirect_to root_url 
    end 
  end

  def auth_actions
    authorize @profile
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      # check_profile_presence
      @profile = current_user.profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:username, :bio, :location, :image, :street_address, :city, :postcode, :state, :country_code, :user_id, :latitude, :longitude)
    end

end 

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_area :username, id: :profile_username %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio, id: :profile_bio %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location, id: :profile_location %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.hidden_field :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address, id: :profile_street_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :profile_city %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.text_field :postcode, id: :profile_postcode %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :profile_state %>
  </div>

  <div class="field">
    <%= form.label :country_code %>
    <%= form.country_select :country_code, priority_countries: ["AU", "NZ"], prompt: "Select a Country" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>



<%= render 'form', profile: @profile %>

<%= link_to 'SHOW', @profile %> |
<%= link_to 'BACK', @profile %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>PROFILES</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Bio</th>
      <th>Location</th>
      <th>Image data</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Street address</th>
      <th>City</th>
      <th>Postcode</th>
      <th>State</th>
      <th>Country code</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.username %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.location %></td>
          <%# <% unless profile.image_data.nil? %> 
            <td><%= image_tag profile.image_display(:thumb) %></td>
        
          <%# <% end %> 
        
  

        <td><%= profile.latitude %></td>
        <td><%= profile.longitude %></td>
        <td><%= profile.street_address %></td>
        <td><%= profile.city %></td>
        <td><%= profile.postcode %></td>
        <td><%= profile.state %></td>
        <td><%= profile.country_code %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'SHOW', profile %></td>

        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# <%= link_to 'New Profile', new_profile_path %> 

app/views/profiles/new.html.erb
<h1>NEW PROFILE</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @profile.username %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<p>
  <strong>Location:</strong>
  <%= @profile.location %>
</p>

<p>
  <strong>Image data:</strong>
  <%= image_tag @profile.image_display(:medium) %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @profile.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @profile.longitude %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @profile.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @profile.city %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @profile.postcode %>
</p>

<p>
  <strong>State:</strong>
  <%= @profile.state %>
</p>

<p>
  <strong>Country code:</strong>
  <%= @profile.country_code %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<% if policy(@profile).update? %>
              <%= link_to 'EDIT', edit_profile_path(@profile) %>
            <% end %> 
<%= link_to 'BACK', @profile_path %>

<%= link_to 'SWAP BEER', new_post_path(@post) %>
<%= link_to 'UPGRADE MEMBERSHIP', memberships_path %>


<td><%= link_to 'DESTROY', @profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>