config/routes.rb
Rails.application.routes.draw do
 
  get 'pages/home'

  get 'pages/contact'

  resources :charges
  resources :payments
  resources :memberships
  get 'pages/index'
  # post 'profiles/index'
  # patch 'profiles/index'
  get 'home/index'
  root "home#index"
  resources :profiles
  resources :posts
  resources :drinks
  devise_for :users
  get 'profiles/edit'
  get 'profiles/show' 
  get 'profiles/new'
  # delete 'profiles/id', to: 'profiles#destroy'
  get 'posts/new'
  # get 'posts/show'
  post 'pages/contact', to: 'pages#contact_email'
  post 'profiles', to: 'profiles#profile'
  post 'posts', to: 'posts#post' 
  get '/tables', to: 'tables#all_tables' 
  get '/tables/table/:table_name', to: 'tables#table', as: 'table'


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  

end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
#   validates :name,  presence: true, uniqueness: true
#   validates :price, presence: true, numericality: { greater_than: 0 }
 
#   def price_in_cents
#     (price * 100).to_i
#   end

# end

# class CreditCard < ActiveRecord::Base
#   belongs_to :user
 
#   before_validation :set_last_digits
 
#   attr_accessor :number, :cvc
 
#   validates :digits, presence: true
#   validates :month, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12 }
#   validates :year, presence: true, numericality: { greater_than_or_equal_to: DateTime.now.year }
 
#   def set_last_digits
#     if number
#       number.to_s.gsub!(/\s/,'')
#       self.digits ||= number.to_s.length <= 4 ? number : number.to_s.slice(-4..-1)
#     end
#   end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.permit(:expiry, :user_id)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership, local: true) do |form| %>
  <% if membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memberships</h1>

<table>
  <thead>
    <tr>
      <th>Expiry</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.expiry %></td>
        <td><%= membership.user %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Expiry:</strong>
  <%= @membership.expiry %>
</p>

<p>
  <strong>User:</strong>
  <%= @membership.user %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>