config/routes.rb
Rails.application.routes.draw do
 
  get 'pages/home'

  get 'pages/contact'

  resources :charges
  resources :payments
  resources :memberships
  get 'pages/index'
  # post 'profiles/index'
  # patch 'profiles/index'
  get 'home/index'
  root "home#index"
  resources :profiles
  resources :posts
  resources :drinks
  devise_for :users
  get 'profiles/edit'
  get 'profiles/show' 
  get 'profiles/new'
  # delete 'profiles/id', to: 'profiles#destroy'
  get 'posts/new'
  # get 'posts/show'
  post 'pages/contact', to: 'pages#contact_email'
  post 'profiles', to: 'profiles#profile'
  post 'posts', to: 'posts#post' 
  get '/tables', to: 'tables#all_tables' 
  get '/tables/table/:table_name', to: 'tables#table', as: 'table'


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>BREWSWAP</h1>


 <div>
 <%# <%= image: ("Brewswap-logo-final.png", class: "logo", alt: "Logo") %>  
<%= image_tag("Brewswap-logo-final.png", class: "logo", alt: "Logo") %>
    <%# <img src="images/Brewswap-logo-final.png" alt="Brewswap logo"> %>
</div>
<%= link_to 'SWAP BEER', new_post_path(@post) %>
<% if user_signed_in? %>
    <% if current_user.profile == nil %>
        <%= link_to 'CREATE PROFILE', new_profile_path(@profile) %>
        <%= link_to 'UPGRADE MEMBERSHIP', memberships_path %>
    <% else %>
        <%= link_to 'UPDATE PROFILE', edit_profile_path(current_user.profile.id) %>
        <%= link_to 'UPGRADE MEMBERSHIP', memberships_path %>
    <% end %>
<% end %>

<%= link_to 'VIEW BEERS AVAILABLE', posts_path %>



<p>Find me in app/views/home/index.html.erb</p>