config/routes.rb
Rails.application.routes.draw do
 
  get 'pages/home'

  get 'pages/contact'

  resources :charges
  resources :payments
  resources :memberships
  get 'pages/index'
  # post 'profiles/index'
  # patch 'profiles/index'
  get 'home/index'
  root "home#index"
  resources :profiles
  resources :posts
  resources :drinks
  devise_for :users
  get 'profiles/edit'
  get 'profiles/show' 
  get 'profiles/new'
  # delete 'profiles/id', to: 'profiles#destroy'
  get 'posts/new'
  # get 'posts/show'
  post 'pages/contact', to: 'pages#contact_email'
  post 'profiles', to: 'profiles#profile'
  post 'posts', to: 'posts#post' 
  get '/tables', to: 'tables#all_tables' 
  get '/tables/table/:table_name', to: 'tables#table', as: 'table'


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  

end

app/models/post.rb
require "mini_magick"

class Post < ApplicationRecord
  include ImageUploader::Attachment.new(:image) # adds an "image" virtual attribute
  belongs_to :user
  has_one :drink
  accepts_nested_attributes_for :drink 
  has_many :likes
  validates :user, presence: true

  def image_display(args)
    if image_data
      image_url(args)
    else
      "http://via.placeholder.com/80x80"
    end
  end
end

app/controllers/posts_controller.rb
require 'drinks_controller.rb'

class PostsController < ApplicationController
#   def set_details        
#     DrinksController.get_details(data)
#   end
    #  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #  before_action :auth_actions, only: [:update, :edit, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  skip_before_action :verify_authenticity_token  


  # def action_that_calls_one_from_another_controller
  #   drinks_controller = DrinksController.new
  #   drinks_controller.request = request
  #   drinks_controller.response = response
  #   drinks_controller.create 
   
  # end
  
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    authorize @posts
    username = Profile.last
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @drink = @post.drink
  end



  # GET /posts/new
  def new
    @post = Post.new
    @drink = Drink.new
    # @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @drink = @post.drink
    # @post.save
    # @drink.save
  end

  # POST /posts
  # POST /posts.json
  def create
    post = Post.new(post_params)
    drink = Drink.new(drink_params)
    # action_that_calls_one_from_another_controller
    # drink.amount_in_ml = params[:amount_in_ml]
    # drink.beer_type = params[:beer_type]
    # drink.number_of_bottles_available = params[:number_of_bottles_available]
    # drink.postcode = params[:postcode]
    # drink.main_ingredient = params[:main_ingredient]

    drink.user = current_user
    post.drink = drink
    post.user = current_user
    
    # authorize @post
    respond_to do |format|
      if post.save && drink.save
        format.html { redirect_to post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    @drink = Drink.find(params[:id]) 
    # @post.drink
    @post.save
    @drink.save
    respond_to do |format|
      if @post.update(post_params) && @drink.update(drink_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @drink = Drink.find(params[:id])
    @drink.destroy
    # if @post.present?
      @post.destroy
    # end
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private

  def auth_actions
   authorize @post 
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image, :amount_in_ml, :number_of_bottles_available, :beer_type, :main_ingredient, :postcode, :user_id)
    end

    def drink_params
      params.require(:drink).permit(:user_id, :amount_in_ml, :number_of_bottles_available, :beer_type, :main_ingredient, :postcode, :post_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.hidden_field :image, value: post.cached_image_data %>
    <%= form.file_field :image %>
  </div>

  <%= render 'partials/drink_details', form: form, drink: @drink %>

<% end %>


    <%# <div class="actions">
    <%= form.submit %>
  <%# </div>  %>

  <%# <%= form_for @post do |post_form| %>
  <%# <%= post_form.fields_for :drink do |drink_fields| %> 
    <%# Amount in ml per bottle : <%= drink_fields.text_field :amount_in_ml %> 
    <%# Number of bottles available: <%= drink_fields.text_field :number_of_bottles_available %> 
    <%# Beer type: <%= drink_fields.text_field :beer_type %> 
    <%# Main ingredient: <%= drink_fields.text_field :main_ingredient %>
    <%# Postcode: <%= drink_fields.text_field :postcode %>
  <%# <% end %>
<%# <% end %> 
  <%# <div class="actions">
    <%= form.submit %>
  <%# </div> %>

app/views/posts/edit.html.erb
<h1>EDITING POST</h1>

<%= render 'form', post: @post, drink: @drink %>

<%= link_to 'SHOW', @post %> |
<%= link_to 'BACK', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<style>

</style>
<h1>POSTS</h1>

<% unless @posts.nil? %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image data</th>
      <th>User</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <%# <% unless post.image_data.nil? %> 
        <td><%= image_tag post.image_display(:thumb) %></td>
        
        <%# <% end %> 
       
        <td><%= link_to 'VIEW USER PROFILE', profile_path(post.user_id) %> </td>  
        <td><%= link_to 'VIEW POST', post %></td>

            <% end %>
 
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'NEW POST', new_post_path %>

app/views/posts/new.html.erb
<h1>NEW POST</h1>

<%= render 'form', post: @post %>

<%= link_to 'BACK', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
<% unless @post.image_data.nil? %>
  <strong>Image:</strong>
  <%= image_tag @post.image_display(:medium) %>
<%end %>
</p>

    <div id="drink_post">
      <%= render 'partials/drink_post', { drink: @drink } %>
    </div>

<%# <p>
  <strong>Profile:</strong>
  <%= @post.profile %>
<%# </p> %>



  <% if policy(@post).update? %>
    <%= link_to 'EDIT', edit_post_path(@post) %> |
  <% end %>
<%= link_to 'BACK', posts_path %>

<td><%= link_to 'DESTROY', @post, method: :delete, data: { confirm: 'Are you sure?' } %></td>